# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TV Shows' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for app
  pod 'SnapKit', '~> 5.0.0'
  pod 'Alamofire', '~> 5.2'
  pod 'SwiftLint'
  pod "PromiseKit", "~> 6.8"
  pod 'ETBinding'
  pod 'JVFloatLabeledTextField'
  
end
